services:
  - type: web
    name: rocomplain-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/admin/me
    autoDeploy: true
